### ISSUE TITLE
Error executing Command: python3 orpheus.py https://www.beatport.com/track/darkside/10844269

### ISSUE THREAD

**Issue by exomarketer** [yarrm80s/orpheusdl#73]
MAC OS Version: 3.13.0 (v3.13.0:60403a5409f, Oct  7 2024, 00:37:40) [Clang 15.0.0 (clang-1500.3.9.4)]

Traceback (most recent call last):
  File "/Users/smart/Desktop/Python/OrpheusDL/orpheus.py", line 225, in <module>
    main()
    ~~~~^^
  File "/Users/smart/Desktop/Python/OrpheusDL/orpheus.py", line 180, in main
    module = orpheus.load_module(service_name)
  File "/Users/smart/Desktop/Python/OrpheusDL/orpheus/core.py", line 210, in load_module
    loaded_module = class_(module_controller)
  File "/Users/smart/Desktop/Python/OrpheusDL/modules/beatport/interface.py", line 54, in __init__
    self.login(module_controller.module_settings['username'], module_controller.module_settings['password'])
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smart/Desktop/Python/OrpheusDL/modules/beatport/interface.py", line 90, in login
    self.valid_account()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/smart/Desktop/Python/OrpheusDL/modules/beatport/interface.py", line 95, in valid_account
    account_data = self.session.get_account()
  File "/Users/smart/Desktop/Python/OrpheusDL/modules/beatport/beatport_api.py", line 93, in get_account
    return self._get('auth/o/introspect')
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smart/Desktop/Python/OrpheusDL/modules/beatport/beatport_api.py", line 88, in _get
    raise ConnectionError(r.text)
ConnectionError: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden

**Comment by johnneerdael** [comment]
I'm suddenly getting the same....

**Comment by Dniel97** [comment]
Fixed, update the module.
